/*
 * Área de Trabalho
 */
package br.edu.unipampa.gerenciadorconcurso.view;

import br.edu.unipampa.gerenciadorconcurso.dao.HibernateUtil;
import br.edu.unipampa.gerenciadorconcurso.view.interno.CadastroCandidato;
import br.edu.unipampa.gerenciadorconcurso.view.interno.SelecaoConcurso;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import org.hibernate.Session;

/**
 * @author Douglas
 * @since 10/01/2015
 */
public class AreaTrabalho extends javax.swing.JFrame {

    /**
     * Creates new form AreaTrabalho
     */
    public AreaTrabalho() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);//deixa maximizado
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaTrabalho = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        atalhoCandidato = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAbrirConcurso = new javax.swing.JMenu();
        itemMenuCadastro = new javax.swing.JMenu();
        itemMenuCandidato = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Área de Trabalho");

        javax.swing.GroupLayout areaTrabalhoLayout = new javax.swing.GroupLayout(areaTrabalho);
        areaTrabalho.setLayout(areaTrabalhoLayout);
        areaTrabalhoLayout.setHorizontalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        areaTrabalhoLayout.setVerticalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        atalhoCandidato.setText("Candidatos");
        atalhoCandidato.setFocusable(false);
        atalhoCandidato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        atalhoCandidato.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        atalhoCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atalhoCandidatoActionPerformed(evt);
            }
        });
        jToolBar1.add(atalhoCandidato);

        menuAbrirConcurso.setText("Abrir Concurso");

        itemMenuCadastro.setText("Cadastro");

        itemMenuCandidato.setText("Candidato");
        itemMenuCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCandidatoActionPerformed(evt);
            }
        });
        itemMenuCadastro.add(itemMenuCandidato);

        menuAbrirConcurso.add(itemMenuCadastro);

        jMenuBar1.add(menuAbrirConcurso);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
            .addComponent(areaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaTrabalho))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="Eventos">

    private void atalhoCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atalhoCandidatoActionPerformed
        criarCadastroCandidato();
    }//GEN-LAST:event_atalhoCandidatoActionPerformed

    private void itemMenuCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCandidatoActionPerformed
        criarCadastroCandidato();
    }//GEN-LAST:event_itemMenuCandidatoActionPerformed
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Inicio">
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Session session = HibernateUtil.openSession();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AreaTrabalho areaTrabalho = new AreaTrabalho();
                areaTrabalho.setVisible(true);
                SelecaoConcurso selecaoConcurso = new SelecaoConcurso(areaTrabalho, true);
                selecaoConcurso.setVisible(true);
                selecaoConcurso.setLocationRelativeTo(null);
            }
        });
    }
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Adicionar Janelas">
    private void adicionarJanela(final JInternalFrame frame) {
        areaTrabalho.add(frame);
        frame.setVisible(true);
        try {
            frame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AreaTrabalho.class.getName()).log(Level.SEVERE, null, ex);
        }
        frame.setIconifiable(true);
        frame.setClosable(true);
        frame.setMaximizable(true);
        frame.setResizable(true);
    }

    private void criarCadastroCandidato() {
        CadastroCandidato cadastroCandidato = new CadastroCandidato();
        adicionarJanela(cadastroCandidato);
    }
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Variaveis">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JButton atalhoCandidato;
    private javax.swing.JMenu itemMenuCadastro;
    private javax.swing.JMenuItem itemMenuCandidato;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuAbrirConcurso;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
}
