/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unipampa.gerenciadorconcurso.view.interno;

import br.edu.unipampa.gerenciadorconcurso.model.Concurso;
import br.edu.unipampa.gerenciadorconcurso.model.Examinador;
import br.edu.unipampa.gerenciadorconcurso.model.Pessoa;
import br.edu.unipampa.gerenciadorconcurso.service.ExaminadorService;
import br.edu.unipampa.gerenciadorconcurso.validator.Campos;
import br.edu.unipampa.gerenciadorconcurso.validator.ComboBoxFormat;
import br.edu.unipampa.gerenciadorconcurso.validator.FieldFormat;
import br.edu.unipampa.gerenciadorconcurso.validator.StatusCadastros;
import br.edu.unipampa.gerenciadorconcurso.view.pesq.PesqExaminador;
import javax.swing.JOptionPane;

/**
 *
 * @author Douglas
 * @since 15/01/2015
 */
public class CadastroExaminador extends javax.swing.JInternalFrame {

    private Campos tratamentoCampos;
    private StatusCadastros status;
    private ExaminadorService examinadorService;
    private Examinador examinador;

    /**
     * Creates new form CadastroBanca
     */
    public CadastroExaminador() {
        initComponents();
        tratamentoCampos = new Campos();
        examinadorService = new ExaminadorService();
        repassarCampos();
        verificaQuantidadeExaminadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btNovo = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        textCodigo = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        textNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        boxSexo = new javax.swing.JComboBox();
        textSexo = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JLabel();
        campoCategoria = new javax.swing.JTextField();
        txtAlertNome = new javax.swing.JLabel();
        txtAlertCategoria = new javax.swing.JLabel();
        campoMensagem = new javax.swing.JTextField();

        setTitle("Cadastro Examinador Banca");

        jToolBar1.setRollover(true);

        btNovo.setText("Novo");
        btNovo.setFocusable(false);
        btNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btNovo);

        btEditar.setText("Editar");
        btEditar.setFocusable(false);
        btEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btEditar);

        btSalvar.setText("Salvar");
        btSalvar.setFocusable(false);
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jToolBar1.add(btSalvar);

        btDeletar.setText("Deletar");
        btDeletar.setFocusable(false);
        btDeletar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDeletar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });
        jToolBar1.add(btDeletar);

        btBuscar.setText("Buscar");
        btBuscar.setFocusable(false);
        btBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(btBuscar);

        textCodigo.setText("Código");

        campoCodigo.setEditable(false);
        campoCodigo.setText("0");
        campoCodigo.setEnabled(false);

        textNome.setText("Nome");

        boxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));

        textSexo.setText("Sexo");

        txtCategoria.setText("Categoria");

        campoCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCategoriaActionPerformed(evt);
            }
        });

        txtAlertNome.setText("!!!");

        txtAlertCategoria.setText("!!!");

        campoMensagem.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
            .addComponent(campoMensagem, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCategoria)
                    .addComponent(textNome)
                    .addComponent(textCodigo)
                    .addComponent(textSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNome)
                    .addComponent(boxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAlertNome)
                    .addComponent(txtAlertCategoria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCodigo)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlertNome))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCategoria)
                    .addComponent(campoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlertCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(campoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtAlertNome.setVisible(false);
        txtAlertCategoria.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        if (!verificaQuantidadeExaminadores()) {
            status.estadoNovo();
        }
    }//GEN-LAST:event_btNovoActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        status.estadoAlterando();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (tratamentoCampos.validaObrigatorios()) {
            Pessoa pessoa = new Pessoa();
            pessoa.setNome(campoNome.getText());
            if (boxSexo.getSelectedIndex() == 0) {
                pessoa.setSexo(true);
            }

            examinador = new Examinador();
            examinador.setPessoa(pessoa);
            examinador.setCategoria(campoCategoria.getText());
            examinador.setConcurso(Concurso.getInstance());
            examinador.setCodigo(Integer.parseInt(campoCodigo.getText()));
            if (examinadorService.salvar(examinador)) {
                status.estadoSalvo();
                campoCodigo.setText(examinador.getCodigo() + "");
                campoMensagem.setText("Examinador salvo com sucesso!");
            } else {
                campoMensagem.setText("Ocorreu um erro ao salvar o candidato!");
            }
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Você deseja realmente deletar o registro?") == JOptionPane.OK_OPTION) {
            if (examinadorService.deletar(Campos.converteNumero(campoCodigo.getText()))) {
                campoMensagem.setText("O registro foi deletado com sucesso!");
                status.estadoNovo();
                verificaQuantidadeExaminadores();
            } else {
                campoMensagem.setText("Ocorreu um problema ao deletar o registro!");
            }
        }
    }//GEN-LAST:event_btDeletarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        PesqExaminador pesqExaminador = new PesqExaminador(null, true, campoCodigo);
        pesqExaminador.setVisible(true);
        if (!campoCodigo.getText().equalsIgnoreCase("0")) {
            int codigo = Campos.converteNumero(campoCodigo.getText());
            examinador = examinadorService.buscar(codigo);

            campoNome.setText(examinador.getPessoa().getNome());
            campoCategoria.setText(examinador.getCategoria());
            if (examinador.getPessoa().getSexo()) {
                boxSexo.setSelectedIndex(0);
            } else {
                boxSexo.setSelectedIndex(1);
            }
            habilitaCampos();
            status.estadoSalvo();
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void campoCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxSexo;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField campoCategoria;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoMensagem;
    private javax.swing.JTextField campoNome;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel textCodigo;
    private javax.swing.JLabel textNome;
    private javax.swing.JLabel textSexo;
    private javax.swing.JLabel txtAlertCategoria;
    private javax.swing.JLabel txtAlertNome;
    private javax.swing.JLabel txtCategoria;
    // End of variables declaration//GEN-END:variables

    private void repassarCampos() {
        tratamentoCampos.setCampo(new ComboBoxFormat(boxSexo));
        tratamentoCampos.setCampo(new FieldFormat(campoNome, txtAlertNome, true));
        tratamentoCampos.setCampo(new FieldFormat(campoCategoria, txtAlertCategoria, true));

        status = new StatusCadastros(btNovo, btDeletar, btSalvar, btSalvar, campoCodigo, campoMensagem, tratamentoCampos);
    }

    private boolean verificaQuantidadeExaminadores() {
        if (examinadorService.buscar(Concurso.getInstance()).size() == 3) {
            JOptionPane.showMessageDialog(null, "Você só pode cadastrar 3 examinadores por concurso.");
            btDeletar.setVisible(false);
            btNovo.setVisible(false);
            btEditar.setVisible(false);
            btSalvar.setVisible(false);
            status.estadoSalvo();
            return true;
        } else {
            btNovo.setVisible(true);
            habilitaCampos();
            return false;
        }
    }

    private void habilitaCampos() {
        btDeletar.setVisible(true);
        btEditar.setVisible(true);
        btSalvar.setVisible(true);
    }
}
