package br.edu.unipampa.gerenciadorconcurso.view.interno;

import br.edu.unipampa.gerenciadorconcurso.model.Concurso;
import br.edu.unipampa.gerenciadorconcurso.model.Pesoprovas;
import br.edu.unipampa.gerenciadorconcurso.service.PesoProvasConcursoService;
import br.edu.unipampa.gerenciadorconcurso.validator.Campos;
import br.edu.unipampa.gerenciadorconcurso.validator.FieldFormat;
import br.edu.unipampa.gerenciadorconcurso.validator.StatusCadastros;
import javax.swing.JOptionPane;

/**
 * DefinirPesoProvasConcurso
 *
 * @version v 1.0 13/01/2015
 * @author Alex Becker
 *
 */
public class DefinirPesoProvasConcurso extends javax.swing.JInternalFrame {

    private Campos tratamentoCampos;
    private StatusCadastros status;
    private PesoProvasConcursoService pesoProvasConcursoService;
    private Pesoprovas pesoprovas;

    public DefinirPesoProvasConcurso() {
        initComponents();
        tratamentoCampos = new Campos();
        pesoProvasConcursoService = new PesoProvasConcursoService();
        repassarCampos();
        buscarPesoCadastrado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btNovo = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        textCodigo = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        textNome = new javax.swing.JLabel();
        textNome1 = new javax.swing.JLabel();
        textNome2 = new javax.swing.JLabel();
        textNome3 = new javax.swing.JLabel();
        campoPesoProvaEscrita = new javax.swing.JTextField();
        txtAlertProvaEscrita = new javax.swing.JLabel();
        campoPesoProvaDidatica = new javax.swing.JTextField();
        txtAlertProvaDidatica = new javax.swing.JLabel();
        campoPesoProvaMemorial = new javax.swing.JTextField();
        txtAlertProvaMemorial = new javax.swing.JLabel();
        campoPesoProvaTitulo = new javax.swing.JTextField();
        txtAlertProvaTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoMensagem = new javax.swing.JTextField();

        setTitle("Definir pesos das provas do concurso");

        jToolBar1.setRollover(true);

        btNovo.setText("Novo");
        btNovo.setFocusable(false);
        btNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btNovo);

        btEditar.setText("Editar");
        btEditar.setFocusable(false);
        btEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btEditar);

        btSalvar.setText("Salvar");
        btSalvar.setFocusable(false);
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jToolBar1.add(btSalvar);

        btDeletar.setText("Deletar");
        btDeletar.setFocusable(false);
        btDeletar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDeletar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });
        jToolBar1.add(btDeletar);

        textCodigo.setText("Código");

        campoCodigo.setEditable(false);
        campoCodigo.setText("0");
        campoCodigo.setEnabled(false);

        textNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textNome.setText("Escrita");

        textNome1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textNome1.setText("Didática");

        textNome2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textNome2.setText("Memorial");

        textNome3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textNome3.setText("Título");

        txtAlertProvaEscrita.setBackground(new java.awt.Color(102, 0, 0));
        txtAlertProvaEscrita.setText("!!!!");
        txtAlertProvaEscrita.setToolTipText("Campo nome é obrigatorio.");

        txtAlertProvaDidatica.setBackground(new java.awt.Color(102, 0, 0));
        txtAlertProvaDidatica.setText("!!!!");
        txtAlertProvaDidatica.setToolTipText("Campo nome é obrigatorio.");

        txtAlertProvaMemorial.setBackground(new java.awt.Color(102, 0, 0));
        txtAlertProvaMemorial.setText("!!!!");
        txtAlertProvaMemorial.setToolTipText("Campo nome é obrigatorio.");

        txtAlertProvaTitulo.setBackground(new java.awt.Color(102, 0, 0));
        txtAlertProvaTitulo.setText("!!!!");
        txtAlertProvaTitulo.setToolTipText("Campo nome é obrigatorio.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Obs.: O somatório dos pesos deve ser igual a 10.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textNome3)
                    .addComponent(textNome2)
                    .addComponent(textNome1)
                    .addComponent(textNome)
                    .addComponent(textCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoPesoProvaTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoPesoProvaMemorial, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoPesoProvaDidatica, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoPesoProvaEscrita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAlertProvaEscrita)
                            .addComponent(txtAlertProvaDidatica)
                            .addComponent(txtAlertProvaMemorial)
                            .addComponent(txtAlertProvaTitulo))))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome)
                    .addComponent(campoPesoProvaEscrita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlertProvaEscrita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome1)
                    .addComponent(campoPesoProvaDidatica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlertProvaDidatica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome2)
                    .addComponent(campoPesoProvaMemorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlertProvaMemorial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome3)
                    .addComponent(campoPesoProvaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlertProvaTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(0, 189, Short.MAX_VALUE))
        );

        txtAlertProvaEscrita.setVisible(false);
        txtAlertProvaEscrita.setVisible(false);
        txtAlertProvaEscrita.setVisible(false);
        txtAlertProvaEscrita.setVisible(false);

        campoMensagem.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(campoMensagem)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        System.out.println("teste: " + campoCodigo.getText().toString());
        if (campoCodigo.getText().equalsIgnoreCase("") || campoCodigo.getText().equalsIgnoreCase("0")) {
            status.estadoNovo();
        } else {
            campoMensagem.setText("Pesos já foram atribuídos para o concurso ativo no sistema. Edite ou exclui o registro caso necessário.");
        }
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (tratamentoCampos.validaObrigatorios()) {
            pesoprovas = new Pesoprovas();
            pesoprovas.setPesoProvaEscrita((float) Double.parseDouble(campoPesoProvaEscrita.getText()));
            pesoprovas.setPesoProvaDidatica((float) Double.parseDouble(campoPesoProvaDidatica.getText()));
            pesoprovas.setPesoProvaMemorial((float) Double.parseDouble(campoPesoProvaMemorial.getText()));
            pesoprovas.setPesoProvaTitulo((float) Double.parseDouble(campoPesoProvaTitulo.getText()));
            pesoprovas.setConcurso(Concurso.getInstance());

            if (!pesoProvasConcursoService.totalPesosCorreto(pesoprovas)) {
                campoMensagem.setText("O somatório dos pesos deve ser igual a 10.");
            } else {
                if (pesoProvasConcursoService.salvar(pesoprovas)) {
                    status.estadoSalvo();
                    campoCodigo.setText(pesoprovas.getCodigo() + "");
                    campoMensagem.setText("Pesos das provas salvo com sucesso!");
                } else {
                    campoMensagem.setText("Ocorreu um erro ao salvar o Pesos das provas!");
                }
            }
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Você deseja realmente deletar o registro?") == JOptionPane.OK_OPTION) {
            if (pesoProvasConcursoService.deletar(Campos.converteNumero(campoCodigo.getText()))) {
                campoMensagem.setText("O registro foi deletado com sucesso!");
                status.estadoNovo();
            } else {
                campoMensagem.setText("Ocorreu um problema ao deletar o registro!");
            }
        }
    }//GEN-LAST:event_btDeletarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        status.estadoAlterando();
    }//GEN-LAST:event_btEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoMensagem;
    private javax.swing.JTextField campoPesoProvaDidatica;
    private javax.swing.JTextField campoPesoProvaEscrita;
    private javax.swing.JTextField campoPesoProvaMemorial;
    private javax.swing.JTextField campoPesoProvaTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel textCodigo;
    private javax.swing.JLabel textNome;
    private javax.swing.JLabel textNome1;
    private javax.swing.JLabel textNome2;
    private javax.swing.JLabel textNome3;
    private javax.swing.JLabel txtAlertProvaDidatica;
    private javax.swing.JLabel txtAlertProvaEscrita;
    private javax.swing.JLabel txtAlertProvaMemorial;
    private javax.swing.JLabel txtAlertProvaTitulo;
    // End of variables declaration//GEN-END:variables

    private void repassarCampos() {
        tratamentoCampos.setCampo(new FieldFormat(campoPesoProvaEscrita, txtAlertProvaEscrita, true));
        tratamentoCampos.setCampo(new FieldFormat(campoPesoProvaDidatica, txtAlertProvaDidatica, true));
        tratamentoCampos.setCampo(new FieldFormat(campoPesoProvaMemorial, txtAlertProvaMemorial, true));
        tratamentoCampos.setCampo(new FieldFormat(campoPesoProvaTitulo, txtAlertProvaTitulo, true));

        status = new StatusCadastros(btNovo, btDeletar, btSalvar, btSalvar, campoCodigo, campoMensagem, tratamentoCampos);
    }

    private void buscarPesoCadastrado() {
        Pesoprovas pesoprovas = pesoProvasConcursoService.buscarPesoProvasConcurso(Concurso.getInstance());
        campoCodigo.setText(pesoprovas.getCodigo().toString());
        campoPesoProvaEscrita.setText("" + pesoprovas.getPesoProvaEscrita());
        campoPesoProvaDidatica.setText("" + pesoprovas.getPesoProvaDidatica());
        campoPesoProvaMemorial.setText("" + pesoprovas.getPesoProvaMemorial());
        campoPesoProvaTitulo.setText("" + pesoprovas.getPesoProvaTitulo());
        status.estadoSalvo();
    }
}
