package br.edu.unipampa.gerenciadorconcurso.view.interno;

import br.edu.unipampa.gerenciadorconcurso.validator.Campos;
import br.edu.unipampa.gerenciadorconcurso.validator.FormattedFieldFormat;
import br.edu.unipampa.gerenciadorconcurso.view.reports.GeradorRelatorios;
import br.edu.unipampa.gerenciadorconcurso.view.reports.Parametro;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import org.exolab.castor.types.Date;

/**
 * Relatório Prova Escrita Ata Sessao Divulgacao Resultado
 *
 * @version v 1.0 19/01/2015
 * @author Alex Becker
 *
 */
public class RelAtaSessaoRealizacaoProvaDidatica extends javax.swing.JInternalFrame {

    private final Campos tratamentoCampos;

    /**
     * Creates new form CadastroCandidato
     */
    public RelAtaSessaoRealizacaoProvaDidatica() {
        initComponents();
        tratamentoCampos = new Campos();
        tratamentoCampos.setCampo(new FormattedFieldFormat(campoData, txtAlertData, true));
//        tratamentoCampos.setCampo(new FormattedFieldFormat(campoHoraInicio, txtAlertHoraInicio, true));
//        tratamentoCampos.setCampo(new FormattedFieldFormat(campoLocal, txtAlertLocal, true));
//        tratamentoCampos.setCampo(new FormattedFieldFormat(campoNroDoc, txtAlertNroDoc, true));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btNovo = new javax.swing.JButton();
        textNascimento = new javax.swing.JLabel();
        campoMensagem = new javax.swing.JTextField();
        txtAlertData = new javax.swing.JLabel();
        campoData = new JFormattedTextField(Campos.createFormatter("##-##-####"));
        ;
        textNascimento1 = new javax.swing.JLabel();
        txtAlertNroDoc = new javax.swing.JLabel();
        campoNroDoc = new javax.swing.JFormattedTextField();
        textNascimento3 = new javax.swing.JLabel();
        txtAlertLocal = new javax.swing.JLabel();
        campoLocal = new javax.swing.JFormattedTextField();

        setTitle("Ata de Sessão de Realização da Prova Didática");

        jToolBar1.setRollover(true);

        btNovo.setText("Gerar Relatório");
        btNovo.setFocusable(false);
        btNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btNovo);

        textNascimento.setText("Data");

        campoMensagem.setEditable(false);

        txtAlertData.setBackground(new java.awt.Color(102, 0, 0));
        txtAlertData.setText("!!!!");
        txtAlertData.setToolTipText("Campo nome é obrigatorio.");

        campoData.setToolTipText("");

        textNascimento1.setText("Nro. Doc.");

        txtAlertNroDoc.setBackground(new java.awt.Color(102, 0, 0));
        txtAlertNroDoc.setText("!!!!");
        txtAlertNroDoc.setToolTipText("Campo nome é obrigatorio.");

        campoNroDoc.setToolTipText("");

        textNascimento3.setText("Local");

        txtAlertLocal.setBackground(new java.awt.Color(102, 0, 0));
        txtAlertLocal.setText("!!!!");
        txtAlertLocal.setToolTipText("Campo nome é obrigatorio.");

        campoLocal.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
            .addComponent(campoMensagem)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(textNascimento1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlertNroDoc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(textNascimento3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlertLocal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(textNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlertData)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(campoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNascimento)
                    .addComponent(txtAlertData)
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNascimento1)
                    .addComponent(txtAlertNroDoc)
                    .addComponent(campoNroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNascimento3)
                    .addComponent(txtAlertLocal)
                    .addComponent(campoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        txtAlertData.setVisible(false);
        txtAlertData.setVisible(false);
        txtAlertData.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        if (tratamentoCampos.validaObrigatorios()) {
            InputStream inputStreamDaImagem = null;
            try {
                String caminhoImagem = System.getProperty("user.dir") + "\\img\\logo_unipampa.png";
                File file = null;
                try {
                    file = new File(caminhoImagem);

                    if (file.exists()) {
                        inputStreamDaImagem = new FileInputStream(file);
                    }
                } catch (FileNotFoundException e) {
                    campoMensagem.setText("Erro ao gerar o relatório. ERRO: " + e.getMessage());
                }

                DateFormat dfmt = new SimpleDateFormat(" d 'de' MMMM 'de' yyyy");
                DateFormat dfmt2 = new SimpleDateFormat("d 'dias do mês de' MMMM 'de' yyyy");
                SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

                String dataRelatorio = campoData.getText().substring(6, 10) + "-" + campoData.getText().substring(3, 5) + "-" + campoData.getText().substring(0, 2);
                java.sql.Time dataRelatorioFormat = new java.sql.Time(format.parse(dataRelatorio).getTime());

                ArrayList<Parametro> parametros = new ArrayList<Parametro>();

                parametros.add(new Parametro("dataRelatorio", dfmt.format(dataRelatorioFormat)));
                parametros.add(new Parametro("local", campoLocal.getText().toString()));
                parametros.add(new Parametro("nroDoc", campoNroDoc.getText().toString()));
                parametros.add(new Parametro("diaExtenso", dfmt2.format(dataRelatorioFormat)));
                parametros.add(new Parametro("candidatos", getCandidatosPresentes()));
                parametros.add(new Parametro("logo", file.getAbsolutePath()));

                GeradorRelatorios.gerar(System.getProperty("user.dir") + "\\src\\relatorios\\RelAtaSessaoRealizacaoProvaDidatica.jasper", parametros);
                campoMensagem.setText("Relatório gerado com sucesso.");
            } catch (Exception e) {
                campoMensagem.setText("Erro ao gerar o relatório. ERRO: " + e.getMessage());
            }

        }
    }//GEN-LAST:event_btNovoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovo;
    private javax.swing.JFormattedTextField campoData;
    private javax.swing.JFormattedTextField campoLocal;
    private javax.swing.JTextField campoMensagem;
    private javax.swing.JFormattedTextField campoNroDoc;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel textNascimento;
    private javax.swing.JLabel textNascimento1;
    private javax.swing.JLabel textNascimento3;
    private javax.swing.JLabel txtAlertData;
    private javax.swing.JLabel txtAlertLocal;
    private javax.swing.JLabel txtAlertNroDoc;
    // End of variables declaration//GEN-END:variables

    
    private String getCandidatosPresentes(){
        //exemplo
        //O candidato 1 compareceu às nove horas e quarenta minutos e apresentou o ponto de número zero com o seguinte título: . 
        //O candidato 2 compareceu às nove horas e quarenta minutos e apresentou o ponto de número zero com o seguinte título: .
        return "";
    }
}
