package br.edu.unipampa.gerenciadorconcurso.view.interno;

import br.edu.unipampa.gerenciadorconcurso.model.Concurso;
import br.edu.unipampa.gerenciadorconcurso.validator.Campos;
import br.edu.unipampa.gerenciadorconcurso.validator.FieldSearchFormat;
import br.edu.unipampa.gerenciadorconcurso.validator.FormattedFieldFormat;
import br.edu.unipampa.gerenciadorconcurso.view.pesq.PesqCandidato;
import br.edu.unipampa.gerenciadorconcurso.view.reports.GeradorRelatorios;
import br.edu.unipampa.gerenciadorconcurso.view.reports.Parametro;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
/**
 * Tela de geração do relatório do termo de desistência do prazo recursal da nota final da prova escrita.
 *
 * @author Douglas Giordano
 * @since 20/01/2015
 */
public class RelAvaliacaoIndividualProvaEscrita extends javax.swing.JInternalFrame {

    private final Campos tratamentoCampos;
    
    /**
     * Creates new form CadastroCandidato
     */
    public RelAvaliacaoIndividualProvaEscrita() {
        initComponents();
        tratamentoCampos = new Campos();
        tratamentoCampos.setCampo(new FormattedFieldFormat(campoData, txtAlertData, true));
        tratamentoCampos.setCampo(new FieldSearchFormat(campoCandidato, txtAlertCandidato, true, txtNomeCandidato, btPesquisarCandidato));
        tratamentoCampos.setCampo(new FieldSearchFormat(campoExaminador, txtAlertExaminador, true, txtNomeExaminador, btPesquisarExaminador));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btGerar = new javax.swing.JButton();
        textNascimento = new javax.swing.JLabel();
        campoMensagem = new javax.swing.JTextField();
        txtAlertData = new javax.swing.JLabel();
        campoData = new JFormattedTextField(Campos.createFormatter("##-##-####"));
        ;
        campoCandidato = new javax.swing.JTextField();
        txtCandidato = new javax.swing.JLabel();
        txtExaminador = new javax.swing.JLabel();
        campoExaminador = new javax.swing.JTextField();
        txtNomeCandidato = new javax.swing.JLabel();
        txtNomeExaminador = new javax.swing.JLabel();
        txtAlertCandidato = new javax.swing.JLabel();
        txtAlertExaminador = new javax.swing.JLabel();
        btPesquisarExaminador = new javax.swing.JButton();
        btPesquisarCandidato = new javax.swing.JButton();

        setTitle("Relatório de Avaliação Individual da Prova Escrita");

        jToolBar1.setRollover(true);

        btGerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/executar.png")));
        btGerar.setText("Gerar Relatório");
        btGerar.setFocusable(false);
        btGerar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btGerar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarActionPerformed(evt);
            }
        });
        jToolBar1.add(btGerar);

        textNascimento.setText("Data");

        campoMensagem.setEditable(false);

        txtAlertData.setBackground(new java.awt.Color(102, 0, 0));
        txtAlertData.setText("!!!!");
        txtAlertData.setToolTipText("Campo nome é obrigatorio.");

        campoData.setToolTipText("");

        campoCandidato.setEditable(false);

        txtCandidato.setText("Candidato");

        txtExaminador.setText("Examinador");

        campoExaminador.setEditable(false);

        txtAlertCandidato.setBackground(new java.awt.Color(102, 0, 0));
        txtAlertCandidato.setText("!!!!");
        txtAlertCandidato.setToolTipText("Campo nome é obrigatorio.");

        txtAlertExaminador.setBackground(new java.awt.Color(102, 0, 0));
        txtAlertExaminador.setText("!!!!");
        txtAlertExaminador.setToolTipText("Campo nome é obrigatorio.");

        btPesquisarExaminador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/executar.png")));
        btPesquisarExaminador.setText("Pesquisar");
        btPesquisarExaminador.setFocusable(false);
        btPesquisarExaminador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisarExaminador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisarExaminador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarExaminadorActionPerformed(evt);
            }
        });

        btPesquisarCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/executar.png")));
        btPesquisarCandidato.setText("Pesquisar");
        btPesquisarCandidato.setFocusable(false);
        btPesquisarCandidato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisarCandidato.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarCandidatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
            .addComponent(campoMensagem)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtExaminador)
                    .addComponent(textNascimento)
                    .addComponent(txtCandidato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCandidato)
                    .addComponent(campoData, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(campoExaminador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btPesquisarExaminador, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlertExaminador)
                        .addGap(11, 11, 11)
                        .addComponent(txtNomeExaminador, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btPesquisarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlertCandidato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAlertData))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNascimento)
                    .addComponent(txtAlertData)
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCandidato)
                        .addComponent(txtNomeCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAlertCandidato))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btPesquisarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtExaminador)
                        .addComponent(campoExaminador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNomeExaminador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAlertExaminador))
                    .addComponent(btPesquisarExaminador, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
        );

        txtAlertData.setVisible(false);
        txtAlertData.setVisible(false);
        txtAlertData.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarActionPerformed
        if (tratamentoCampos.validaObrigatorios()) {
            InputStream inputStreamDaImagem = null;
            try {
                String caminhoImagem = System.getProperty("user.dir") + "\\img\\logo_unipampa.png";
                File file = null;
                try {
                    file = new File(caminhoImagem);

                    if (file.exists()) {
                        inputStreamDaImagem = new FileInputStream(file);
                    }
                } catch (FileNotFoundException e) {
                    campoMensagem.setText("Erro ao gerar o relatório. ERRO: " + e.getMessage());
                }

                ArrayList<Parametro> parametros = new ArrayList<Parametro>();
                parametros.add(new Parametro("dataRelatorio", campoData.getText()));
                parametros.add(new Parametro("candidato", campoCandidato.getText()));
                parametros.add(new Parametro("examinador", txtNomeExaminador.getText()));
                parametros.add(new Parametro("concurso", Concurso.getInstance().getCodigo()+""));
                parametros.add(new Parametro("logo", file.getAbsolutePath()));

                GeradorRelatorios.gerar(System.getProperty("user.dir") + "\\src\\relatorios\\RelAvaliacaoIndividualProvaEscrita.jasper", parametros);
                campoMensagem.setText("Relatório gerado com sucesso.");
            } catch (Exception e) {
                campoMensagem.setText("Erro ao gerar o relatório. ERRO: " + e.getMessage());
            }

        }
    }//GEN-LAST:event_btGerarActionPerformed

    private void btPesquisarExaminadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarExaminadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPesquisarExaminadorActionPerformed

    private void btPesquisarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarCandidatoActionPerformed
        PesqCandidato pesqCandidato = new PesqCandidato(null, closable, campoCandidato, txtNomeCandidato);
    }//GEN-LAST:event_btPesquisarCandidatoActionPerformed

    //<editor-fold defaultstate="collapsed" desc="variaveis">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerar;
    private javax.swing.JButton btPesquisarCandidato;
    private javax.swing.JButton btPesquisarExaminador;
    private javax.swing.JTextField campoCandidato;
    private javax.swing.JFormattedTextField campoData;
    private javax.swing.JTextField campoExaminador;
    private javax.swing.JTextField campoMensagem;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel textNascimento;
    private javax.swing.JLabel txtAlertCandidato;
    private javax.swing.JLabel txtAlertData;
    private javax.swing.JLabel txtAlertExaminador;
    private javax.swing.JLabel txtCandidato;
    private javax.swing.JLabel txtExaminador;
    private javax.swing.JLabel txtNomeCandidato;
    private javax.swing.JLabel txtNomeExaminador;
    // End of variables declaration//GEN-END:variables
    
//</editor-fold>
}
